import { join } from 'node:path';
import { existsSync, readFileSync, watch as fsWatch, type FSWatcher } from 'node:fs';
import { loadConfig } from '../lib/generators/config.js';
import { analyzeStorybook } from '../lib/navigation/analyze-storybook.js';
import { validate, type Diagnostic } from '../lib/navigation/validate.js';
import { flatten } from '../lib/navigation/flatten.js';
import { extractParams } from '../lib/navigation/extract-params.js';
import { mergeRouteParams } from '../lib/navigation/merge-route-params.js';
import { renderNative } from '../lib/navigation/render-native.js';
import { renderWeb } from '../lib/navigation/render-web.js';
import { renderRoutesDts } from '../lib/navigation/render-routes-dts.js';
import { safeWrite } from '../lib/generators/write.js';
import { log } from '../util/log.js';

export interface BuildNavOptions {
  cwd: string;
  /** Re-run the build whenever a storybook source changes. */
  watch?: boolean;
  /**
   * Overwrite pre-existing non-generated files. The four AUTO-GENERATED outputs
   * are always force-overwritten (they are owned by the generator); `force` is
   * carried for surface parity with the other generators and future outputs.
   */
  force?: boolean;
}

/** Import specifier the generated navigation pulls screen components from. */
const SCREENS_IMPORT = './screens';

const BARREL = [
  '// AUTO-GENERATED by sublime build:nav — do not edit',
  "export { Navigation } from './navigation.js';",
  "export type { AppRoutes } from './routes.js';",
  '',
].join('\n');

function printDiagnostics(platform: string, diagnostics: Diagnostic[]): void {
  for (const d of diagnostics) {
    log.error(`[${platform}] ${d.rule}: ${d.message}`);
  }
}

/**
 * Compile the per-platform storybooks into navigation artifacts.
 *
 * Loads `storybook.native.ts` (mobile) and `storybook.web.ts` (web) from the
 * project's `navigationDir`, validates each against its platform's rules, and —
 * only when both are clean — renders and force-writes the four generated files
 * (`navigation.native.tsx`, `navigation.tsx`, `routes.d.ts`, `index.ts`).
 * On any validation error it prints diagnostics and writes nothing.
 *
 * @returns process exit code (0 success, 1 on validation/load failure).
 */
export async function buildNav(opts: BuildNavOptions): Promise<number> {
  const cfg = loadConfig(opts.cwd);
  const navDir = join(opts.cwd, cfg.navigationDir);
  const nativeFile = join(navDir, 'storybook.native.ts');
  const webFile = join(navDir, 'storybook.web.ts');

  const code = await buildOnce(navDir, nativeFile, webFile);

  if (opts.watch) {
    watchAndRebuild(navDir, nativeFile, webFile);
    // In watch mode the process stays alive; report the first build's result.
  }

  return code;
}

/** Run a single load → validate → render → write pass. */
async function buildOnce(navDir: string, nativeFile: string, webFile: string): Promise<number> {
  // A project only carries the storybooks for the targets it was scaffolded with
  // (a web-only app has no storybook.native.ts). Analyze only what exists; require
  // at least one.
  const hasNative = existsSync(nativeFile);
  const hasWeb = existsSync(webFile);
  if (!hasNative && !hasWeb) {
    log.error(
      `build:nav: no storybook found in ${navDir} (expected storybook.web.ts and/or storybook.native.ts).`,
    );
    return 1;
  }

  let nativeRoot;
  let webRoot;
  try {
    nativeRoot = hasNative ? analyzeStorybook(nativeFile) : undefined;
    webRoot = hasWeb ? analyzeStorybook(webFile) : undefined;
  } catch (err) {
    log.error(err instanceof Error ? err.message : String(err));
    return 1;
  }

  const diagnostics = [
    ...(nativeRoot ? validate(nativeRoot, 'mobile').map((d) => ['native', d] as const) : []),
    ...(webRoot ? validate(webRoot, 'web').map((d) => ['web', d] as const) : []),
  ];
  if (diagnostics.length > 0) {
    for (const [platform, d] of diagnostics) printDiagnostics(platform, [d]);
    log.error(`build:nav failed with ${diagnostics.length} error(s); wrote nothing.`);
    return 1;
  }

  // Param types are erased by the runtime import; recover the explicit
  // `page<...>()` type arguments by scanning each platform's source.
  const nativeParams = hasNative
    ? extractParams(readFileSync(nativeFile, 'utf8'))
    : new Map<string, string>();
  const webParams = hasWeb
    ? extractParams(readFileSync(webFile, 'utf8'))
    : new Map<string, string>();

  // Each platform may have its own pages (spec §2.4/§10) — union both flattened
  // trees into one AppRoutes route map; conflicting param types are an error.
  const { routes, conflicts } = mergeRouteParams({
    nativeKeys: nativeRoot ? flatten(nativeRoot).routes.map((r) => r.key) : [],
    webKeys: webRoot ? flatten(webRoot).routes.map((r) => r.key) : [],
    nativeParams,
    webParams,
  });
  if (conflicts.length > 0) {
    for (const key of conflicts) {
      log.error(
        `route-param-conflict ${key}: native and web declare different param types for "${key}". ` +
          `Fix: make both page<...>() type arguments agree.`,
      );
    }
    log.error(`build:nav failed with ${conflicts.length} error(s); wrote nothing.`);
    return 1;
  }

  const dtsSrc = renderRoutesDts(routes);

  // Generated files are owned by the generator: force-overwrite unconditionally.
  // Only the platforms that actually have a storybook get a navigation file. The
  // web variant is the platform-neutral *base* file (`navigation.tsx`): tsc and web
  // bundlers resolve `./navigation` to it, while Metro overrides it with
  // `navigation.native.tsx` on native — the same base/`.native` split as the
  // `./screens` barrel.
  if (nativeRoot) {
    safeWrite(
      join(navDir, 'navigation.native.tsx'),
      renderNative(nativeRoot, { screensImport: SCREENS_IMPORT }),
      true,
    );
  }
  if (webRoot) {
    safeWrite(
      join(navDir, 'navigation.tsx'),
      renderWeb(webRoot, { screensImport: SCREENS_IMPORT }),
      true,
    );
  }
  safeWrite(join(navDir, 'routes.d.ts'), dtsSrc, true);
  safeWrite(join(navDir, 'index.ts'), BARREL, true);

  const count = (nativeRoot ? 1 : 0) + (webRoot ? 1 : 0) + 2;
  log.success(`build:nav wrote ${count} files to ${navDir}`);
  return 0;
}

/**
 * Watch both storybook sources and re-run the build (debounced) on change.
 * Long-lived: the returned watchers keep the process alive until interrupted.
 */
function watchAndRebuild(navDir: string, nativeFile: string, webFile: string): FSWatcher[] {
  log.info(`build:nav watching ${navDir} — Ctrl-C to stop.`);
  let timer: ReturnType<typeof setTimeout> | undefined;
  const trigger = (): void => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      void buildOnce(navDir, nativeFile, webFile);
    }, 50);
  };
  return [nativeFile, webFile].map((file) => fsWatch(file, trigger));
}
