// AUTO-GENERATED by sublime build:nav — do not edit
import type { ReactNode } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';
import { NavProvider } from '@sublime-ui/ui/navigation';
import { useWebNav } from '@sublime-ui/ui/navigation/bridge.web';
import { Home, ProductDetail, Profile } from './screens';

const paths: Record<string, string> = {
  "home": "/home",
  "product": "/product",
  "profile": "/settings/profile",
};

export const titles: Record<string, { title?: string; icon?: string }> = {
  "home": { title: "Home" },
  "product": { title: "Product" },
  "profile": { title: "Profile" },
};

function pathOf(name: string, params?: unknown): string {
  let path = paths[name] ?? '/';
  if (params && typeof params === 'object') {
    for (const [k, v] of Object.entries(params as Record<string, unknown>)) {
      path = path.replace(`:${k}`, String(v));
    }
  }
  return path;
}

function nameOf(path: string): string {
  const norm = (p: string) => (p.length > 1 && p.endsWith('/') ? p.slice(0, -1) : p);
  const target = norm(path);
  for (const [name, p] of Object.entries(paths)) {
    const pattern = norm(p);
    if (pattern === target) return name;
    // Match parameterized routes (':id' segments) positionally.
    if (pattern.includes(':')) {
      const re = new RegExp('^' + pattern.replace(/:[^/]+/g, '[^/]+') + '$');
      if (re.test(target)) return name;
    }
  }
  return path;
}

function Sidebar() {
  return <Outlet />;
}

function Stack() {
  return <Outlet />;
}

function NavBridge({ children }: { children: ReactNode }) {
  const nav = useWebNav(pathOf, nameOf);
  return <NavProvider value={nav}>{children}</NavProvider>;
}

export function Navigation() {
  return (
    <BrowserRouter>
      <NavBridge>
        <Routes>
      <Route path="/" element={<Sidebar />}>
        <Route path="home" element={<Home />} />
        <Route path="product" element={<ProductDetail />} />
      <Route path="settings" element={<Stack />}>
        <Route path="profile" element={<Profile />} />
      </Route>
      </Route>
        </Routes>
      </NavBridge>
    </BrowserRouter>
  );
}
