/** A route plus the TS type string for its navigation params (default `void`). */
export interface RouteParam {
  /** Flattened route key (e.g. `home`, `product`). */
  key: string;
  /** Declared param type string captured from the page (e.g. `{ id: number }`). */
  params: string;
}

/**
 * Emit a `routes.d.ts` source string mapping each route key to its param type.
 *
 * Produces an exported `AppRoutes` interface the app feeds to
 * `useNav<AppRoutes>()`, e.g.
 *
 * ```ts
 * export interface AppRoutes {
 *   home: void;
 *   product: { id: number };
 * }
 * ```
 */
export function renderRoutesDts(routes: RouteParam[]): string {
  const header = '// AUTO-GENERATED by sublime build:nav — do not edit';

  const entries = routes
    .map((r) => `  ${r.key}: ${r.params};`)
    .join('\n');

  return (
    `${header}\n` +
    `export interface AppRoutes {\n` +
    `${entries}\n` +
    `}\n`
  );
}
