import { flatten } from './flatten.js';
import type { PrintFormat, RouteNode } from './model.js';

export interface RenderWebOptions {
  /** Import specifier the generated file pulls screen components from. */
  screensImport: string;
}

/** Map a book `format` to its generated web layout component name. */
const WEB_LAYOUT: Record<string, string> = {
  sidebar: 'Sidebar',
  tabs: 'Tabs',
  stack: 'Stack',
};

function layoutFor(format: PrintFormat | undefined): string {
  return WEB_LAYOUT[format ?? 'stack'] ?? WEB_LAYOUT.stack!;
}

/** PascalCase a route key into a generated component name. */
function pascal(key: string): string {
  return key
    .replace(/[_\s-]+/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/** kebab-case a route key for a URL segment. */
function kebab(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

/**
 * Emit a `navigation.web.tsx` source string from a storybook `RouteNode` tree.
 * Each `book` becomes a layout component (chosen by `format`) wrapping
 * `<Outlet/>`; each `page` becomes a child `<Route>`. The exported `Navigation`
 * component renders a `<Routes>` tree and bridges the runtime `useWebNav`
 * (driven by the generated `pathOf`/`nameOf` maps) through `<NavProvider>`.
 */
export function renderWeb(root: RouteNode, opts: RenderWebOptions): string {
  const screenNames = new Set<string>();
  const layoutNames = new Set<string>();
  const layoutBlocks: string[] = [];

  /**
   * Render a book node into a `<Route>` element string. A book with a
   * `path` ?? `/` index becomes a layout wrapper route; its page children
   * become child `<Route>`s; nested books recurse.
   */
  const renderBook = (book: RouteNode, isRoot: boolean): string => {
    const layout = layoutFor(book.format);
    layoutNames.add(layout);

    const segment = book.options.path ?? kebab(book.key);
    const routePath = isRoot ? '/' : segment;

    const children: string[] = [];
    for (const child of book.children ?? []) {
      if (child.kind === 'page') {
        const comp = child.component ?? pascal(child.key);
        screenNames.add(comp);
        const childSegment = child.options.path ?? kebab(child.key);
        // `initial: true` maps to react-router's index route (the parent's `/`).
        if (child.options.initial === true) {
          children.push(`        <Route index element={<${comp} />} />`);
        }
        children.push(
          `        <Route path="${childSegment}" element={<${comp} />} />`,
        );
      } else {
        children.push(renderBook(child, false));
      }
    }

    return (
      `      <Route path="${routePath}" element={<${layout} />}>\n` +
      `${children.join('\n')}\n` +
      `      </Route>`
    );
  };

  const routesTree = renderBook(root, true);

  // Layout component definitions (one per used format), each wrapping <Outlet/>.
  for (const layout of [...layoutNames].sort()) {
    layoutBlocks.push(
      `function ${layout}() {\n` +
        `  return <Outlet />;\n` +
        `}`,
    );
  }

  // pathOf / nameOf maps from the flattened route table.
  const { routes } = flatten(root);
  const pathEntries = routes
    .map((r) => `  ${JSON.stringify(r.key)}: ${JSON.stringify(r.path)},`)
    .join('\n');

  // titles map: per route key, its label/icon (from PageOptions). Web layouts
  // (sidebar/tabs) read this to render chrome; `stack` ignores the icon.
  const titleEntries: string[] = [];
  const collectTitles = (node: RouteNode): void => {
    if (node.kind === 'page') {
      const fields: string[] = [];
      if (node.options.title !== undefined) fields.push(`title: ${JSON.stringify(node.options.title)}`);
      if (node.options.icon !== undefined) fields.push(`icon: ${JSON.stringify(node.options.icon)}`);
      if (fields.length > 0) {
        titleEntries.push(`  ${JSON.stringify(node.key)}: { ${fields.join(', ')} },`);
      }
      return;
    }
    for (const child of node.children ?? []) collectTitles(child);
  };
  collectTitles(root);

  const screenImport = [...screenNames].sort().join(', ');

  const header = '// AUTO-GENERATED by sublime build:nav — do not edit';

  return (
    `${header}\n` +
    `import type { ReactNode } from 'react';\n` +
    `import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';\n` +
    `import { NavProvider } from '@sublime-ui/ui/navigation';\n` +
    `import { useWebNav } from '@sublime-ui/ui/navigation/bridge.web';\n` +
    `import { ${screenImport} } from '${opts.screensImport}';\n` +
    `\n` +
    `const paths: Record<string, string> = {\n` +
    `${pathEntries}\n` +
    `};\n` +
    `\n` +
    `export const titles: Record<string, { title?: string; icon?: string }> = {\n` +
    `${titleEntries.join('\n')}${titleEntries.length > 0 ? '\n' : ''}` +
    `};\n` +
    `\n` +
    `function pathOf(name: string, params?: unknown): string {\n` +
    `  let path = paths[name] ?? '/';\n` +
    `  if (params && typeof params === 'object') {\n` +
    `    for (const [k, v] of Object.entries(params as Record<string, unknown>)) {\n` +
    `      path = path.replace(\`:\${k}\`, String(v));\n` +
    `    }\n` +
    `  }\n` +
    `  return path;\n` +
    `}\n` +
    `\n` +
    `function nameOf(path: string): string {\n` +
    `  const norm = (p: string) => (p.length > 1 && p.endsWith('/') ? p.slice(0, -1) : p);\n` +
    `  const target = norm(path);\n` +
    `  for (const [name, p] of Object.entries(paths)) {\n` +
    `    const pattern = norm(p);\n` +
    `    if (pattern === target) return name;\n` +
    `    // Match parameterized routes (':id' segments) positionally.\n` +
    `    if (pattern.includes(':')) {\n` +
    `      const re = new RegExp('^' + pattern.replace(/:[^/]+/g, '[^/]+') + '$');\n` +
    `      if (re.test(target)) return name;\n` +
    `    }\n` +
    `  }\n` +
    `  return path;\n` +
    `}\n` +
    `\n` +
    `${layoutBlocks.join('\n\n')}\n` +
    `\n` +
    `function NavBridge({ children }: { children: ReactNode }) {\n` +
    `  const nav = useWebNav(pathOf, nameOf);\n` +
    `  return <NavProvider value={nav}>{children}</NavProvider>;\n` +
    `}\n` +
    `\n` +
    `export function Navigation() {\n` +
    `  return (\n` +
    `    <BrowserRouter>\n` +
    `      <NavBridge>\n` +
    `        <Routes>\n` +
    `${routesTree}\n` +
    `        </Routes>\n` +
    `      </NavBridge>\n` +
    `    </BrowserRouter>\n` +
    `  );\n` +
    `}\n`
  );
}
