import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  mkdirSync,
  copyFileSync,
  writeFileSync,
  readFileSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { parse, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildNav } from '../../src/commands/build-nav.js';

// `buildNav` dynamic-imports the storybooks by file URL. Under vitest that runs
// through vite-node, whose loader mishandles percent-encoded URLs (the worktree
// path contains a space). We assemble the fixture app in a clean temp root whose
// path needs no encoding. (Plain Node — the shipped CLI — handles this fine.)
const cleanTmpRoot = join(parse(tmpdir()).root, 'sublime-devkit-tests');
const nativeFixtureSrc = fileURLToPath(
  new URL('../fixtures/nav-app/src/navigation/storybook.native.ts', import.meta.url),
);

// A minimal web storybook using web-valid formats (sidebar/stack).
const WEB_STORYBOOK = `import { book, link, page } from '@sublime-ui/ui/navigation';

export function Home() {
  return null;
}

export function ProductDetail() {
  return null;
}

export function Profile() {
  return null;
}

const settingsBook = book({
  format: 'stack',
  pages: {
    profile: page(Profile, { title: 'Profile' }),
  },
});

export default book({
  format: 'sidebar',
  pages: {
    home: page(Home, { title: 'Home' }),
    product: page<{ id: number }>(ProductDetail, { title: 'Product' }),
    settings: link(settingsBook, { title: 'Settings' }),
  },
});
`;

// A bottomNav book with 6 direct pages — violates the bottomNav-max-5 rule.
const SIX_PAGE_NATIVE = `import { book, page } from '@sublime-ui/ui/navigation';

export function A() { return null; }
export function B() { return null; }
export function C() { return null; }
export function D() { return null; }
export function E() { return null; }
export function F() { return null; }

export default book({
  format: 'bottomNav',
  pages: {
    a: page(A, { title: 'A' }),
    b: page(B, { title: 'B' }),
    c: page(C, { title: 'C' }),
    d: page(D, { title: 'D' }),
    e: page(E, { title: 'E' }),
    f: page(F, { title: 'F' }),
  },
});
`;

let dir = '';
let navDir = '';
beforeEach(() => {
  mkdirSync(cleanTmpRoot, { recursive: true });
  dir = mkdtempSync(join(cleanTmpRoot, 'build-nav-'));
  navDir = join(dir, 'src', 'navigation');
  mkdirSync(navDir, { recursive: true });
});
afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('buildNav', () => {
  it('compiles valid storybooks into the four navigation files', async () => {
    copyFileSync(nativeFixtureSrc, join(navDir, 'storybook.native.ts'));
    writeFileSync(join(navDir, 'storybook.web.ts'), WEB_STORYBOOK);

    const code = await buildNav({ cwd: dir });
    expect(code).toBe(0);

    const native = join(navDir, 'navigation.native.tsx');
    const web = join(navDir, 'navigation.web.tsx');
    const dts = join(navDir, 'routes.d.ts');
    const barrel = join(navDir, 'index.ts');

    expect(existsSync(native)).toBe(true);
    expect(existsSync(web)).toBe(true);
    expect(existsSync(dts)).toBe(true);
    expect(existsSync(barrel)).toBe(true);

    const nativeSrc = readFileSync(native, 'utf8');
    expect(nativeSrc).toContain('// AUTO-GENERATED by sublime build:nav');
    expect(nativeSrc).toContain('createBottomTabNavigator');
    expect(nativeSrc).toContain('export function Navigation()');

    const webSrc = readFileSync(web, 'utf8');
    expect(webSrc).toContain('react-router-dom');
    expect(webSrc).toContain('export function Navigation()');

    const dtsSrc = readFileSync(dts, 'utf8');
    expect(dtsSrc).toContain('export interface AppRoutes');
    expect(dtsSrc).toContain('home: void;');

    const barrelSrc = readFileSync(barrel, 'utf8');
    expect(barrelSrc).toContain('./navigation');
    expect(barrelSrc).toContain('./routes');
  });

  it('returns non-zero and writes nothing when a bottomNav book has 6 pages', async () => {
    writeFileSync(join(navDir, 'storybook.native.ts'), SIX_PAGE_NATIVE);
    writeFileSync(join(navDir, 'storybook.web.ts'), WEB_STORYBOOK);

    const code = await buildNav({ cwd: dir });
    expect(code).not.toBe(0);

    expect(existsSync(join(navDir, 'navigation.native.tsx'))).toBe(false);
    expect(existsSync(join(navDir, 'navigation.web.tsx'))).toBe(false);
    expect(existsSync(join(navDir, 'routes.d.ts'))).toBe(false);
    expect(existsSync(join(navDir, 'index.ts'))).toBe(false);
  });
});
