import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the per-component documentation instance.
 * Auto-generated from the components/ folder structure.
 * Each subfolder's _category_.json controls its label and position.
 */
const sidebars: SidebarsConfig = {
  componentsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
